CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    email_normalized VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_app_user_email_normalized UNIQUE (email_normalized),
    CONSTRAINT ck_app_user_email_normalized_lower CHECK (email_normalized = lower(email_normalized))
);

CREATE TABLE restaurant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000),
    address VARCHAR(300),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_restaurant_name UNIQUE (name)
);

CREATE TABLE menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000),
    price_krw INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_menu_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (id),
    CONSTRAINT uq_menu_restaurant_name UNIQUE (restaurant_id, name),
    CONSTRAINT ck_menu_price_nonnegative CHECK (price_krw IS NULL OR price_krw >= 0)
);

CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    overall_score SMALLINT NOT NULL,
    taste_score SMALLINT NOT NULL,
    value_score SMALLINT NOT NULL,
    portion_score SMALLINT NOT NULL,
    comment VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_review_menu FOREIGN KEY (menu_id) REFERENCES menu (id),
    CONSTRAINT uq_review_user_menu UNIQUE (user_id, menu_id),
    CONSTRAINT ck_review_overall_score CHECK (overall_score BETWEEN 1 AND 5),
    CONSTRAINT ck_review_taste_score CHECK (taste_score BETWEEN 1 AND 5),
    CONSTRAINT ck_review_value_score CHECK (value_score BETWEEN 1 AND 5),
    CONSTRAINT ck_review_portion_score CHECK (portion_score BETWEEN 1 AND 5),
    CONSTRAINT ck_review_comment_length CHECK (comment IS NULL OR char_length(comment) <= 1000)
);

CREATE INDEX idx_menu_restaurant_id ON menu (restaurant_id);
CREATE INDEX idx_review_menu_id ON review (menu_id);
CREATE INDEX idx_review_user_id ON review (user_id);
