-- New Supabase application schema. Existing Flyway files and hosted data are untouched.
-- Legacy numeric restaurant/menu/review IDs are retained; auth identities use UUIDs.

CREATE SCHEMA private;

CREATE TABLE public.profiles (
    user_id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    display_name text NOT NULL DEFAULT '회원',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_profiles_display_name_length
        CHECK (char_length(btrim(display_name)) BETWEEN 1 AND 80)
);
COMMENT ON TABLE public.profiles IS
    'Public display name only. Email, password hashes, legacy IDs, and roles are never stored here.';

CREATE TABLE public.restaurants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    description varchar(1000),
    address varchar(300),
    region varchar(120),
    latitude numeric(9, 6),
    longitude numeric(9, 6),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_restaurants_name UNIQUE (name),
    CONSTRAINT ck_restaurants_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90.000000 AND 90.000000),
    CONSTRAINT ck_restaurants_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180.000000 AND 180.000000),
    CONSTRAINT ck_restaurants_coordinates_pair
        CHECK ((latitude IS NULL) = (longitude IS NULL))
);

CREATE TABLE private.legacy_user_identity (
    legacy_user_id bigint PRIMARY KEY,
    auth_user_id uuid NOT NULL UNIQUE REFERENCES auth.users (id) ON DELETE RESTRICT,
    legacy_email_normalized varchar(320) NOT NULL UNIQUE,
    legacy_must_change_password boolean NOT NULL DEFAULT false,
    mapped_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_legacy_user_email_normalized_lower
        CHECK (legacy_email_normalized = lower(legacy_email_normalized))
);
COMMENT ON TABLE private.legacy_user_identity IS
    'Private, one-time migration identity map. Never expose legacy IDs or email through the Data API.';

CREATE TABLE private.user_roles (
    user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE RESTRICT,
    role_code text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_code),
    CONSTRAINT ck_user_roles_role_code CHECK (role_code IN ('SERVER_ADMIN'))
);
COMMENT ON TABLE private.user_roles IS
    'Trusted role assignments. Client-editable Auth metadata and public profiles are not authorization sources.';

CREATE TABLE private.restaurant_owners (
    user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE RESTRICT,
    restaurant_id bigint NOT NULL REFERENCES public.restaurants (id) ON DELETE RESTRICT,
    assigned_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, restaurant_id)
);
CREATE INDEX idx_private_restaurant_owners_restaurant
    ON private.restaurant_owners (restaurant_id, user_id);

-- Preserve imported legacy rights metadata privately if present. New uploads do not
-- create or attest to rights claims, and this table is not part of the public API.
CREATE TABLE private.legacy_media_rights (
    legacy_media_id varchar(64) PRIMARY KEY,
    rights_basis varchar(500),
    rights_attested_at timestamptz,
    rights_attested_legacy_user_id bigint,
    retained_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.menus (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id bigint NOT NULL REFERENCES public.restaurants (id) ON DELETE RESTRICT,
    name varchar(160) NOT NULL,
    description varchar(1000),
    price_krw integer,
    cuisine_category varchar(24) NOT NULL DEFAULT 'OTHER',
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_menus_restaurant_name UNIQUE (restaurant_id, name),
    CONSTRAINT ck_menus_price_nonnegative CHECK (price_krw IS NULL OR price_krw >= 0),
    CONSTRAINT ck_menus_cuisine_category
        CHECK (cuisine_category IN ('KOREAN', 'WESTERN', 'CHINESE', 'JAPANESE', 'SNACK', 'PUB', 'CAFE', 'OTHER'))
);
CREATE INDEX idx_menus_restaurant_active ON public.menus (restaurant_id, active, id);

CREATE TABLE public.reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE RESTRICT,
    menu_id bigint NOT NULL REFERENCES public.menus (id) ON DELETE RESTRICT,
    overall_score numeric(2, 1) NOT NULL,
    taste_score numeric(2, 1),
    value_score numeric(2, 1),
    portion_score numeric(2, 1),
    comment varchar(1000),
    non_event_review_consent boolean,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_reviews_user_menu UNIQUE (user_id, menu_id),
    CONSTRAINT ck_reviews_overall_score
        CHECK (overall_score BETWEEN 0.5 AND 5.0 AND overall_score * 2 = trunc(overall_score * 2)),
    CONSTRAINT ck_reviews_taste_score
        CHECK (taste_score IS NULL OR (taste_score BETWEEN 0.5 AND 5.0 AND taste_score * 2 = trunc(taste_score * 2))),
    CONSTRAINT ck_reviews_value_score
        CHECK (value_score IS NULL OR (value_score BETWEEN 0.5 AND 5.0 AND value_score * 2 = trunc(value_score * 2))),
    CONSTRAINT ck_reviews_portion_score
        CHECK (portion_score IS NULL OR (portion_score BETWEEN 0.5 AND 5.0 AND portion_score * 2 = trunc(portion_score * 2))),
    CONSTRAINT ck_reviews_comment_length
        CHECK (comment IS NULL OR char_length(comment) <= 1000)
);
CREATE INDEX idx_reviews_menu_created ON public.reviews (menu_id, created_at DESC, id DESC);
CREATE INDEX idx_reviews_user_created ON public.reviews (user_id, created_at DESC, id DESC);
CREATE INDEX idx_reviews_menu_overall ON public.reviews (menu_id, overall_score DESC);
CREATE INDEX idx_reviews_menu_taste ON public.reviews (menu_id, taste_score DESC);
CREATE INDEX idx_reviews_menu_value ON public.reviews (menu_id, value_score DESC);
CREATE INDEX idx_reviews_menu_portion ON public.reviews (menu_id, portion_score DESC);

CREATE TABLE public.media_assets (
    id uuid PRIMARY KEY DEFAULT pg_catalog.gen_random_uuid(),
    object_path text NOT NULL UNIQUE,
    media_kind text NOT NULL,
    uploaded_by uuid NOT NULL REFERENCES auth.users (id) ON DELETE RESTRICT,
    -- menu_id is an upload target and is protected by the upload-intent RPC. It is
    -- deliberately not an ownership source; the menu row and owner mapping are.
    menu_id bigint REFERENCES public.menus (id) ON DELETE RESTRICT,
    -- review_id records the upload target only. The authoritative review attachment
    -- is public.review_photos, whose FK cascades when a review is removed.
    review_id bigint,
    content_type text NOT NULL,
    original_bytes bigint NOT NULL,
    stored_bytes bigint NOT NULL,
    sha256_hex varchar(64),
    lifecycle_status text NOT NULL DEFAULT 'PENDING',
    created_at timestamptz NOT NULL DEFAULT now(),
    activated_at timestamptz,
    CONSTRAINT ck_media_assets_kind CHECK (media_kind IN ('MENU', 'REVIEW')),
    CONSTRAINT ck_media_assets_target CHECK (
        (media_kind = 'MENU' AND menu_id IS NOT NULL AND review_id IS NULL)
        OR (media_kind = 'REVIEW' AND menu_id IS NULL AND review_id IS NOT NULL)
    ),
    CONSTRAINT ck_media_assets_content_type
        CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp')),
    CONSTRAINT ck_media_assets_original_bytes
        CHECK (original_bytes > 0 AND original_bytes < 100000000),
    CONSTRAINT ck_media_assets_stored_bytes
        CHECK (stored_bytes > 0 AND stored_bytes < 100000000),
    CONSTRAINT ck_media_assets_sha256
        CHECK (sha256_hex IS NULL OR sha256_hex ~ '^[0-9a-fA-F]{64}$'),
    CONSTRAINT ck_media_assets_lifecycle_status
        CHECK (lifecycle_status IN ('PENDING', 'ACTIVE', 'REVOKED', 'DELETE_PENDING', 'DELETED')),
    CONSTRAINT ck_media_assets_object_path
        CHECK (object_path =
            CASE media_kind
                WHEN 'MENU' THEN 'menu/' || uploaded_by::text || '/' || id::text ||
                    CASE content_type WHEN 'image/jpeg' THEN '.jpg' WHEN 'image/png' THEN '.png' ELSE '.webp' END
                WHEN 'REVIEW' THEN 'review/' || uploaded_by::text || '/' || id::text ||
                    CASE content_type WHEN 'image/jpeg' THEN '.jpg' WHEN 'image/png' THEN '.png' ELSE '.webp' END
            END)
);
CREATE INDEX idx_media_assets_uploader_status ON public.media_assets (uploaded_by, lifecycle_status);
CREATE INDEX idx_media_assets_menu_target ON public.media_assets (menu_id) WHERE media_kind = 'MENU';
CREATE INDEX idx_media_assets_review_target ON public.media_assets (review_id) WHERE media_kind = 'REVIEW';
COMMENT ON COLUMN public.media_assets.lifecycle_status IS
    'PENDING upload; ACTIVE linked and attachable; DELETE_PENDING detached and queued for retry; DELETED physically removed; REVOKED inactive.';

CREATE TABLE private.legacy_media_asset_identity (
    legacy_media_id varchar(64) PRIMARY KEY,
    media_id uuid NOT NULL UNIQUE REFERENCES public.media_assets (id) ON DELETE RESTRICT,
    mapped_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE private.legacy_media_asset_identity IS
    'Private mapping from legacy media identifiers to new Storage-backed asset UUIDs.';

ALTER TABLE public.menus
    ADD COLUMN photo_media_id uuid REFERENCES public.media_assets (id) ON DELETE RESTRICT,
    ADD CONSTRAINT uq_menus_photo_media UNIQUE (photo_media_id);

CREATE TABLE public.review_photos (
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE CASCADE,
    media_id uuid NOT NULL UNIQUE REFERENCES public.media_assets (id) ON DELETE RESTRICT,
    sort_order smallint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (review_id, media_id),
    CONSTRAINT ck_review_photos_sort_order CHECK (sort_order >= 0)
);
CREATE INDEX idx_review_photos_review_order ON public.review_photos (review_id, sort_order, media_id);

CREATE TABLE public.review_likes (
    user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, review_id)
);
CREATE INDEX idx_review_likes_review ON public.review_likes (review_id, user_id);

CREATE TABLE public.menu_wishlists (
    user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    menu_id bigint NOT NULL REFERENCES public.menus (id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, menu_id)
);
CREATE INDEX idx_menu_wishlists_menu ON public.menu_wishlists (menu_id, user_id);

CREATE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
BEGIN
    NEW.updated_at := pg_catalog.now();
    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated, service_role;

CREATE TRIGGER trg_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_restaurants_updated_at
    BEFORE UPDATE ON public.restaurants
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_menus_updated_at
    BEFORE UPDATE ON public.menus
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE FUNCTION public.guard_review_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
BEGIN
    IF NEW.user_id IS DISTINCT FROM OLD.user_id
       OR NEW.menu_id IS DISTINCT FROM OLD.menu_id
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'review identity fields are immutable';
    END IF;
    NEW.updated_at := pg_catalog.now();
    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.guard_review_update() FROM PUBLIC, anon, authenticated, service_role;
CREATE TRIGGER trg_reviews_guard_update
    BEFORE UPDATE ON public.reviews
    FOR EACH ROW EXECUTE FUNCTION public.guard_review_update();

CREATE FUNCTION public.handle_new_auth_user_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
DECLARE
    v_display_name text;
BEGIN
    v_display_name := pg_catalog.btrim(NEW.raw_user_meta_data ->> 'display_name');
    IF v_display_name IS NULL OR v_display_name = '' THEN
        v_display_name := '회원';
    END IF;
    IF pg_catalog.char_length(v_display_name) > 80 THEN
        v_display_name := pg_catalog.left(v_display_name, 80);
    END IF;
    INSERT INTO public.profiles (user_id, display_name)
    VALUES (NEW.id, v_display_name)
    ON CONFLICT (user_id) DO NOTHING;
    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.handle_new_auth_user_profile() FROM PUBLIC, anon, authenticated, service_role;
CREATE TRIGGER trg_auth_user_profile_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user_profile();

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_wishlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.legacy_user_identity ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.restaurant_owners ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.legacy_media_rights ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.legacy_media_asset_identity ENABLE ROW LEVEL SECURITY;
